spring.application.name=create-url-service
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener_db
spring.datasource.username=jesson
spring.datasource.password=whatsoever
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true



